#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         8
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#D8645A"
bspc config normal_border_color "#709775"
bspc config click_to_focus false
bspc config focus_follows_pointer true

feh --bg-scale /home/cy/Pictures/altchalk.jpg
picom

